version: "3"

services:
  nginx:
    image: docker.io/nginx:alpine
    container_name: reading-point-frontend
    restart: unless-stopped
    ports:
      - "8900:8000"

    volumes:
      - ./site.conf:/etc/nginx/conf.d/site.conf:ro
      - ./dist:/var/www/html/dist:ro

     
    networks:
      - reading-point-frontend-network
      
networks:
  reading-point-frontend-network:
    driver: bridge
    name: reading-point-frontend-network
